name: Linting

on:
  pull_request:
    types: [opened, synchronize, reopened, labeled, unlabeled]

jobs:
  styles:
    name: Lint CSS

    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Use Node LTS version
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Lint CSS files
        run: yarn lint:styles
      